# Generated by Django 3.2.9 on 2021-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Fees_Counter',
            field=models.IntegerField(default=0),
        ),
    ]
