# Generated by Django 3.2.9 on 2021-11-15 11:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('intuition', '0003_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_name',
            name='Description',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
