# Generated by Django 3.2.9 on 2022-02-12 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intuition', '0005_remove_students_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidAmt', models.IntegerField(default=0)),
                ('DateOfPayment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Payment')),
                ('Name', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='intuition.students')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Log',
            },
        ),
    ]
