# Generated by Django 3.2.9 on 2022-02-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intuition', '0006_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='intuition.students'),
        ),
    ]
