# Generated by Django 3.2.9 on 2022-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intuition', '0007_alter_log_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='certid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Certificate ID'),
        ),
    ]
